baseURL = "https://yeuua114.github.io/solar-lamp-b2b/"
languageCode = "en-us"
title = "Solar Lamp B2B Supplier"

[security]
  allowContent = ['! ^text/html$']
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['^https?://', '! ^https?://127\.', '! ^https?://localhost', '! (?i)https://[^/#]*@']
  [security.node]
    [security.node.permissions]
      allowAddons = ['tailwindcss']
      allowChildProcess = ['tailwindcss']
      allowRead = ['.', '../', '/']
      allowWorker = ['tailwindcss']
      allowWrite = []
      disable = false
